DROP TABLE IF EXISTS `entity_order`;
CREATE TABLE `entity_order` ( 
    ID INT NOT NULL AUTO_INCREMENT,
    UserID INT NOT NULL,
    CustomerAddress VARCHAR(200) NOT NULL,
    CustomerName VARCHAR(50) NOT NULL,
    ShippingType VARCHAR(50) NOT NULL,
    ShippingCost FLOAT NOT NULL,
    SubTotal FLOAT NOT NULL,
    Tax FLOAT NOT NULL,
    Total FLOAT NOT NULL,
    CreatedOn TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UpdatedOn TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    IsActive bit(1) NOT NULL DEFAULT b'1',
    PRIMARY KEY (ID)
    );